### ISSUE TITLE
Colons followed by spaces

### ISSUE THREAD

**Issue by eherle** [gbonnema/rabo2ofx#4] opened 2021-11-15 16:33 UTC
Many thanks for this python script, @gbonnema. Great work.
I have been testing it (in Windows 10), in order to kill my Excel-copy-paste workflow for importing Rabo transactions. I have a question about the second booking line as a result of the import. E.g.:
`OFX ext. info: |Trans type:Transfer|Memo:Studietoelage Xxxx + Yyyy`
This line is not recognized by GnuCash. Could it be caused by the fact that there is no space between `Memo:` and `Studietoelage`?
Is it possible to add spaces after the colons by default, so that GnuCash recognizes the imported bookings based on previous imports?

**Comment by gbonnema** [comment] 2021-11-15 17:15
Hi Eric, I don´t get it. Is the 2nd line part of the Rabo import file? Or is it the ofx file? My ofx file has no such line. If you execute the script on the rabo import file, then you get a directory (ofx for gnucash) with xml. The output you show is not xml, but I don't know what it is. 

I have the following query:

1. What version of gnucash are you using?
2. What version of rabo2ofx are you using (can find it in the comments of the script)
3. What are the first few lines of the ofx-file (including the offending 2nd line)? Anonymize any account info or other personal info. 
4. What are the corresponding input lines from the rabo import file? Again, anonymize!

For illustration, this is my output file (first few lines without any booking).

```
<OFX>
   <SIGNONMSGSRSV1>
      <SONRS>                            <!-- Begin signon -->
         <STATUS>                        <!-- Begin status aggregate -->
            <CODE>0</CODE>               <!-- OK -->
            <SEVERITY>INFO</SEVERITY>
         </STATUS>
         <DTSERVER>20200330</DTSERVER>   <!-- Oct. 29, 1999, 10:10:03 am -->
         <LANGUAGE>ENG</LANGUAGE>        <!-- Language used in response -->
         <DTPROFUP>20200330</DTPROFUP>   <!-- Last update to profile-->
         <DTACCTUP>20200330</DTACCTUP>   <!-- Last account update -->
         <FI>                            <!-- ID of receiving institution -->
            <ORG>NCH</ORG>               <!-- Name of ID owner -->
            <FID>1001</FID>              <!-- Actual ID -->
         </FI>
      </SONRS>                           <!-- End of signon -->
   </SIGNONMSGSRSV1>
   <BANKMSGSRSV1>
      <STMTTRNRS>                        <!-- Begin response -->
         <TRNUID>1001</TRNUID>           <!-- Client ID sent in request -->
         <STATUS>                     <!-- Start status aggregate -->
            <CODE>0</CODE>            <!-- OK -->
            <SEVERITY>INFO</SEVERITY>
         </STATUS>
        <STMTRS>                         <!-- Begin statement response -->
           <CURDEF>EUR</CURDEF>
           <BANKACCTFROM>                <!-- Identify the account -->
              <BANKID>RABONL2U</BANKID> <!-- Routing transit or other FI ID -->
              <ACCTID>NL89RABO99999999</ACCTID> <!-- Account number -->
              <ACCTTYPE>CHECKING</ACCTTYPE><!-- Account type -->
           </BANKACCTFROM>               <!-- End of account ID -->
           <BANKTRANLIST>                <!-- Begin list of statement trans. -->

```
And the first few transaction is:

              <DTSTART>20181230</DTSTART>
              <DTEND>20200101</DTEND>
                  <STMTTRN>
                     <TRNTYPE>OTHER</TRNTYPE>
                     <DTPOSTED>20181230</DTPOSTED>
                     <TRNAMT>-63.38</TRNAMT>
                     <FITID>NL99RABO99999999990000000000000013530</FITID>
                     <NAME>[db] diverse boekingen 9999999 RABOBANK NEDERLAND</NAME>
                     <BANKACCTTO>
                        <BANKID></BANKID>
                        <ACCTID>09999999999</ACCTID>
                        <ACCTTYPE>CHECKING</ACCTTYPE>
                     </BANKACCTTO>
                     <MEMO>Kaartnummer: xxxx   Zie rekeningoverzicht 24-12-2018</MEMO>
                  </STMTTRN>

As you can see, memo looks quite different. No spaces required.

**Comment by eherle** [comment] 2021-11-15 22:44
Sorry, I was not very clear. The second line I am referring to is the second line of the imported booking as GnuCash is showing.
In the ofx file the specific line for this booking is: `<MEMO>Studietoelage Xxxx + Yyyyy </MEMO>`. That looks healthy to me. So, I guess the problem is caused by the OFX import function then.

To answer your questions:
1. What version of gnucash are you using?
*4.8 on Windows 10*
2. What version of rabo2ofx are you using (can find it in the comments of the script)
*rabo2ofx version 2.13 (gbo: [2019-08-23] Added OFX booking codes)*
3. What are the first few lines of the ofx-file (including the offending 2nd line)? Anonymize any account info or other personal info.
```
<OFX>
   <SIGNONMSGSRSV1>
      <SONRS>                            <!-- Begin signon -->
         <STATUS>                        <!-- Begin status aggregate -->
            <CODE>0</CODE>               <!-- OK -->
            <SEVERITY>INFO</SEVERITY>
         </STATUS>
         <DTSERVER>20211115</DTSERVER>   <!-- Oct. 29, 1999, 10:10:03 am -->
         <LANGUAGE>ENG</LANGUAGE>        <!-- Language used in response -->
         <DTPROFUP>20211115</DTPROFUP>   <!-- Last update to profile-->
         <DTACCTUP>20211115</DTACCTUP>   <!-- Last account update -->
         <FI>                            <!-- ID of receiving institution -->
            <ORG>NCH</ORG>               <!-- Name of ID owner -->
            <FID>1001</FID>              <!-- Actual ID -->
         </FI>
      </SONRS>                           <!-- End of signon -->
   </SIGNONMSGSRSV1>
   <BANKMSGSRSV1>
      <STMTTRNRS>                        <!-- Begin response -->
         <TRNUID>1001</TRNUID>           <!-- Client ID sent in request -->
         <STATUS>                     <!-- Start status aggregate -->
            <CODE>0</CODE>            <!-- OK -->
            <SEVERITY>INFO</SEVERITY>
         </STATUS>
        <STMTRS>                         <!-- Begin statement response -->
           <CURDEF>EUR</CURDEF>
           <BANKACCTFROM>                <!-- Identify the account -->
              <BANKID>RABONL2U</BANKID> <!-- Routing transit or other FI ID -->
              <ACCTID>NLxxRABOxxxxxxxxxx</ACCTID> <!-- Account number -->
              <ACCTTYPE>CHECKING</ACCTTYPE><!-- Account type -->
           </BANKACCTFROM>               <!-- End of account ID -->
           <BANKTRANLIST>                <!-- Begin list of statement trans. -->
              <DTSTART>20211001</DTSTART>
              <DTEND>20211101</DTEND>
                  <STMTTRN>
                     <TRNTYPE>OTHER</TRNTYPE>
                     <DTPOSTED>20211009</DTPOSTED>
                     <TRNAMT>-xxx.xx</TRNAMT>
                     <FITID>NLxxRABOxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</FITID>
                     <NAME>[db] diverse boekingen</NAME>
                     <BANKACCTTO>
                        <BANKID></BANKID>
                        <ACCTID></ACCTID>
                        <ACCTTYPE>CHECKING</ACCTTYPE>
                     </BANKACCTTO>
                     <MEMO>Eff.nota Kwartaalafrek. beleggen   xxxxxxx  xxxxxxxx</MEMO>
                  </STMTTRN>
              </BANKTRANLIST>                   <!-- End list of statement                       trans. -->
              <LEDGERBAL>                       <!-- Ledger balance                   aggregate -->
               <BALAMT>0</BALAMT>
               <DTASOF>199910291120</DTASOF><!-- Bal date: 10/29/99, 11:20 am -->
            </LEDGERBAL>                      <!-- End ledger balance -->
         </STMTRS>
        <STMTRS>                         <!-- Begin statement response -->
           <CURDEF>EUR</CURDEF>
           <BANKACCTFROM>                <!-- Identify the account -->
              <BANKID>RABONL2U</BANKID> <!-- Routing transit or other FI ID -->
              <ACCTID>NLxxRABOxxxxxxxxxx</ACCTID> <!-- Account number -->
              <ACCTTYPE>CHECKING</ACCTTYPE><!-- Account type -->
           </BANKACCTFROM>               <!-- End of account ID -->
           <BANKTRANLIST>                <!-- Begin list of statement trans. -->
              <DTSTART>20211001</DTSTART>
              <DTEND>20211101</DTEND>
                  <STMTTRN>
                     <TRNTYPE>XFER</TRNTYPE>
                     <DTPOSTED>20211001</DTPOSTED>
                     <TRNAMT>+xxx.xx</TRNAMT>
                     <FITID>NLxxRABOxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</FITID>
                     <NAME>NLxxRABOxxxxxxxxxx X.X. Xxxxx xx</NAME>
                     <BANKACCTTO>
                        <BANKID></BANKID>
                        <ACCTID>NLxxRABOxxxxxxxxxx</ACCTID>
                        <ACCTTYPE>CHECKING</ACCTTYPE>
                     </BANKACCTTO>
                     <MEMO>Studietoelage Xxxxx + Yyyyy</MEMO>
                  </STMTTRN>
```         
4. What are the corresponding input lines from the rabo import file? Again, anonymize
```
"IBAN/BBAN","Munt","BIC","Volgnr","Datum","Rentedatum","Bedrag","Saldo na trn","Tegenrekening IBAN/BBAN","Naam tegenpartij","Naam uiteindelijke partij","Naam initiërende partij","BIC tegenpartij","Code","Batch ID","Transactiereferentie","Machtigingskenmerk","Incassant ID","Betalingskenmerk","Omschrijving-1","Omschrijving-2","Omschrijving-3","Reden retour","Oorspr bedrag","Oorspr munt","Koers"
"NLxxRABOxxxxxxxxxx","EUR","RABONL2U","000000000000000125","2021-10-10","2021-10-09","-xxx,xx","+xxx,xx","","","","","","db","","","","","","Eff.nota Kwartaalafrek. beleggen   xxxxxxxxx  xxxxxxxxx"," ","","","","",""
"NLxxRABOxxxxxxxxxx","EUR","RABONL2U","000000000000013030","2021-10-01","2021-10-01","+xxx,xx","+xxxx,xx","NLxxRABOxxxxxxxxxx","X.X. Xxxxx xx","","","RABONL2U","tb","","","","","","Studietoelage Xxxxx + Yyyyyy"," ","","","","",""

```

**Comment by gbonnema** [comment] 2021-11-16 08:23
> Sorry, I was not very clear. The second line I am referring to is the second line of the imported booking as GnuCash is showing.
> In the ofx file the specific line for this booking is: <MEMO>Studietoelage Xxxx + Yyyyy </MEMO>. That looks healthy to me. 

Ok, now I understand. You get some kind of error message when importing in gnucash. Let me check and see if I can reproduce any  error. It might be helpful if you could show me the error  you get.

**Comment by gbonnema** [comment] 2021-11-16 16:10
I could not reproduce the error. What I could reproduce is the fact that gnucash does not recognize all bookings into the right account. Those that it does not recognize I have to change manually to point to the right account. For example when first receiving funds from "studietoelage" gnucash will not recognize the booking. So manually I would assign it to an account, like "expenses:study". If none exists yet, I would create it. 

In the past I had a mapping mechanism to recognize future booking from the same source. That seems to have change in gnucash, so I assume it is now more automatic. 

Let me know if this helps and if the problem is indeed gnucash only. Awaiting response.

**Comment by eherle** [comment] 2021-11-16 18:15
Yes, I suspect the problem is GnuCash only. Or better, I am the problem myself 😒. Up till now I imported transactions as CSV files and I have not used the OFX import. I need to make mileage first with the OFX import, before I can exclude myself as the root cause.
Up till now I used an Excel to dump all descriptive fields in one single line with spaces in between. In ofx terms, all these fields where assembled in the \<NAME\> field, which produced one single line in the account view in Gnucash. Now I need to display two lines to see the memo field content as well.
The other thing is that the import produces a number of red lines. As soon as I enable these lines to import them, they get assigned to the right account (based on the bayesian import rules). Maybe if I run this monthly import a couple more times, these red lines will no longer appear and be assigned to the right account right away. So, I think I need to practice a little more first.

Many thanks for your swift response and support. And many thanks once more for this script. I really like how you can prevent the import of two transactions for one single transaction between accounts at the same bank. Makes your reconciliation life much easier.

**Comment by gbonnema** [comment] 2021-11-16 18:23
Well, I guess I can close this issue. Let me know if anything new occurs. As a ps. do check for each red line what the cause is. Often one can ignore and just enable them, but sometimes the red line is relevant. Thanks for the reply. Closing issue.

**Closed as completed by gbonnema** 2021-11-16 18:23 UTC
